// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace loterry_console.Models;

public partial class DatosQuiniela
{
    public int Idregistro { get; set; }

    public string Nombre { get; set; }

    public string Previa { get; set; }

    public string Primera { get; set; }

    public string Matutina { get; set; }

    public string Vespertina { get; set; }

    public string Tarde { get; set; }

    public string Nocturna { get; set; }

    public string FechaDiaPublicacion { get; set; }
}