// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace loterry_console.Models;

public partial class DatosQuiniela
{
    public int Idregistro { get; set; }

    public string Nombre { get; set; }

    public int? Previa { get; set; }

    public int? Primera { get; set; }

    public int? Matutina { get; set; }

    public int? Vespertina { get; set; }

    public int? Tarde { get; set; }

    public int? Nocturna { get; set; }

    public string FechaDiaPublicacion { get; set; }
}