// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using loterry_console.DB;
using Microsoft.EntityFrameworkCore;

namespace loterry_console.Models;

public partial class quinielaContext : DbContext
{
    public quinielaContext()
    {
    }

    public quinielaContext(DbContextOptions<quinielaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DatosQuiniela> DatosQuiniela { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer(Connect.connectDB());

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DatosQuiniela>(entity =>
        {
            entity.HasKey(e => e.Idregistro).HasName("PK__datos_qu__917BB529C7C005D2");

            entity.ToTable("datos_quiniela");

            entity.Property(e => e.Idregistro).HasColumnName("idregistro");
            entity.Property(e => e.FechaDiaPublicacion)
                .HasMaxLength(20)
                .HasColumnName("fecha_dia_publicacion");
            entity.Property(e => e.Matutina).HasColumnName("matutina");
            entity.Property(e => e.Nocturna).HasColumnName("nocturna");
            entity.Property(e => e.Nombre)
                .HasMaxLength(20)
                .HasColumnName("nombre");
            entity.Property(e => e.Previa).HasColumnName("previa");
            entity.Property(e => e.Primera).HasColumnName("primera");
            entity.Property(e => e.Tarde).HasColumnName("tarde");
            entity.Property(e => e.Vespertina).HasColumnName("vespertina");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}